### ISSUE TITLE
是否支持nodejs v8.x ？

### ISSUE THREAD

**Issue by linxuanwei** [hyj1991/v8-cpu-analysis#4]

**Comment by hyj1991** [comment]
@linxuanwei v8.x 这个工具是支持的，但是 v8.x 下你要导出 Heapsnapshot 的话要么使用 v8-profiler，要么使用 heapdump，我测试过 v8-profiler 目前在 8.x 下导出 Heapsnapshot 有问题，heapdump 可以正常使用

如果你在 8.x 下想继续使用 v8-profiler 的话，可以尝试下这个 https://www.npmjs.com/package/v8-profiler-node8
